exclude: ^roles/geerlingguy.*$

repos:
- repo: https://github.com/ansible-community/ansible-lint.git
  rev: v5.0.2
  hooks:
    - id: ansible-lint

- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 2.1.5
  hooks:
    - id: shellcheck

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
