---
- hosts: all


- name: install dockers and k8s on all machines
  import_playbook: tests/aws.cluster/ansible/install-k8s.yml

- name: initialize master 
  import_playbook: tests/aws.cluster/ansible/master-playbook.yml

- name: deploy the EdgeNet software to the k8s cluster
  import_playbook: tests/aws.cluster/ansible/deploy-edgenet.yml

- name: prerequisites for edgenet worker node deployment
  import_playbook: tests/aws.cluster/ansible/edgenet-preset.yml

- name: deploy edgenet worker node
  import_playbook: edgenet-aws-node.yml