---
- hosts: all

- name: set up k8s users
  import_playbook: tests/local.cluster/users.yml

- name: install dockers and k8s on all machines
  import_playbook: tests/local.cluster/install-k8s.yml

- name: initialize master 
  import_playbook: tests/local.cluster/master-playbook.yml

- name: join workers to k8s cluster
  import_playbook: tests/local.cluster/join-workers.yml

- name: set up edgenet service
  import_playbook: edgenet-node.yml