---
- hosts: all
  become: true
  tasks:
    - name: Ensure Calico CNI binaries are absent
      file:
        path: "{{ item }}"
        state: absent
      with_fileglob: /opt/cni/bin/*calico*

    - name: Ensure Calico CNI configurations are absent
      file:
        path: "{{ item }}"
        state: absent
      with_fileglob: /etc/cni/net.d/*calico*

    - name: Reboot the node
      reboot:
