---
- hosts: all

- name: set up k8s users
  import_playbook: tests/aws.cluster/ansible/users.yml

- name: install dockers and k8s on all machines
  import_playbook: tests/aws.cluster/ansible/install-k8s.yml

- name: initialize master 
  import_playbook: tests/aws.cluster/ansible/master-playbook.yml

- name: join workers to k8s cluster
  import_playbook: tests/aws.cluster/ansible/join-workers.yml

- name: prerequisites for edgenet deployment
  import_playbook: tests/aws.cluster/ansible/edgenet-preset.yml