---
- hosts: all
  become: true
  tasks:
    - name: Clean packages
      apt:
        autoclean: true
        autoremove: true
      when: ansible_os_family == 'Debian'

    - name: Ensure packages are up-to-date
      apt:
        update_cache: true
        upgrade: true
      when: ansible_os_family == 'Debian'

    - name: Clean packages
      yum:
        autoremove: true
      when: ansible_os_family == 'RedHat'

    - name: Ensure Delta RPMs are enabled
      yum:
        name: deltarpm
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Ensure packages are up-to-date
      yum:
        name: '*'
        state: latest
      when: ansible_os_family == 'RedHat'
