---
collections:
  - name: ansible.posix
    version: 1.1.1

  - name: community.general
    version: 1.3.2

  - name: community.kubernetes
    version: 1.1.1

roles:
  - name: geerlingguy.docker
    version: 3.0.0

  - name: geerlingguy.kubernetes
    version: 4.0.2

  - name: geerlingguy.swap
    version: 1.0.2

  - name: willshersystems.sshd
    version: v0.12.0
