---
# community.kubernetes.k8s requirement
- name: Install openshift Python package
  pip:
    executable: pip3
    name: openshift

# TODO: Get the config from the EdgeNet website instead
- name: kubeconfig
  get_url:
    url: https://raw.githubusercontent.com/EdgeNet-project/edgenet/master/configs/public.cfg
    dest: /tmp/public.cfg
    mode: '0444'

- name: Get my public IP
  community.general.ipify_facts:
    timeout: 10

- name: Create the NodeContribution object
  community.kubernetes.k8s:
    state: present
    kubeconfig: /tmp/public.cfg
    definition:
      apiVersion: v1
      kind: NodeContribution
      metadata:
        name: "{{ edgenet_node_name }}"
        namespace: "{{ edgenet_node_namespace }}"
      spec:
        host: "{{ ipify_public_ip }}"
        port: "{{ edgenet_ssh_port }}"
        user: "{{ edgenet_ssh_user }}"
        enabled: true
