---
# Simplified version of
# - https://github.com/geerlingguy/ansible-role-containerd (MIT)
- name: Ensure containerd YUM GPG keys is present
  rpm_key:
    key: "{{ containerd_yum_gpg_key }}"
    state: present

- name: Ensure containerd YUM repository is present
  get_url:
    url: "{{ containerd_yum_repo_url }}"
    dest: '/etc/yum.repos.d/docker-ce.repo'
    owner: root
    group: root
    mode: 0644

- name: Ensure containerd is not version-locked
  lineinfile:
    path: /etc/yum/pluginconf.d/versionlock.list
    line: "0:containerd.io*"
    state: absent

- name: Ensure containerd is installed and up-to-date
  tags: ['skip_ansible_lint']
  yum:
    name: "containerd.io-*{{ containerd_version }}*"
    state: latest
    update_cache: true
  notify: restart containerd

- name: Ensure containerd is version-locked
  lineinfile:
    path: /etc/yum/pluginconf.d/versionlock.list
    line: "0:containerd.io*"
    state: present
