---
- include_tasks: kube-debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: kube-redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Ensure kubelet is started and enabled at boot
  systemd:
    name: kubelet
    state: started
    enabled: true
