---
- include_tasks: kube-debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: kube-redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Ensure kubelet is enabled at boot (state={{ edgenet_service_state }})
  systemd:
    name: kubelet
    state: "{{ edgenet_service_state }}"
    enabled: true
