---
- name: Disable swap
  include_tasks: swap.yml

# This is to simplify future Ansible calls, since by default
# it uses /usr/bin/python which does not exist on Ubuntu.
- name: Ensure python is python3 on Ubuntu
  apt:
    name: python-is-python3
    state: present
  # TODO: Symbolic link on old Ubuntu versions
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version != '18.04'

# This is a (temporary?) hack to fix an issue with Google's Kubernetes repository.
# E: Failed to fetch https://packages.cloud.google.com/apt/dists/kubernetes-xenial/main/binary-arm64/by-hash/SHA256/536531faf6df19cafb3ee304de5ed6787c3b5a1c20f1223dcbe6fd70ff9f93bb  404  Not Found [IP: 2404:6800:4004:81f::200e 443]
- name: Ensure APT uses IPv4
  copy:
    dest: /etc/apt/apt.conf.d/99force-ipv4
    mode: "0644"
    content: 'Acquire::ForceIPv4 "true";'
  when: ansible_os_family == 'Debian'

- name: Ensure `yum-plugin-versionlock` is installed
  yum:
    name: 'yum-plugin-versionlock'
    state: present
  when: ansible_os_family == 'RedHat'

- name: Install containerd
  include_tasks: containerd.yml

- name: Install Kubernetes
  include_tasks: kube.yml

- name: Install Wireguard
  include_tasks: wireguard.yml

# Kubernetes required modules and network configuration
# https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#letting-iptables-see-bridged-traffic
# https://kubernetes.io/docs/setup/production-environment/container-runtimes/
- name: Ensure Kubernetes kernel modules are loaded on boot
  copy:
    src: modules-k8s.conf
    dest: /etc/modules-load.d/k8s.conf
    mode: "0644"

- name: Ensure Kubernetes kernel modules are loaded for the session
  tags: ['skip_ansible_lint']
  command:
    cmd: "modprobe {{ item }}"
  loop:
    - br_netfilter
    - ip_conntrack
    - ip_tables
    - overlay
  # This may fail in some environment (e.g. Armbian Docker build).
  ignore_errors: true

# Firewalld seems to conflict with ipt/nf and drop incoming traffic on the VPN interface.
- name: Ensure firewalld is disabled
  systemd:
    name: firewalld
    enabled: false
    state: stopped
  # Ignore error if firewalld is not installed.
  ignore_errors: true

- name: Ensure iptables can see bridged traffic
  sysctl:
    name: "{{ item }}"
    value: "1"
    state: present
  loop:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables
    - net.ipv4.ip_forward

- name: Ensure conntrack table size is large enough
  sysctl:
    name: net.netfilter.nf_conntrack_max
    value: "1000000"
    state: present

# Fix an issue with CoreDNS on systems running systemd-resolved
# See https://coredns.io/plugins/loop/#troubleshooting-loops-in-kubernetes-clusters
- name: Check if systemd-resolved is in use
  stat:
    path: /run/systemd/resolve/resolv.conf
  register: resolved_resolv_conf

- name: Ensure native DNS resolvers are used
  file:
    src: /run/systemd/resolve/resolv.conf
    dest: /etc/resolv.conf
    mode: "0644"
    state: link
    # In case /etc/resolv.conf is a file and not a symlink
    force: true
  when: resolved_resolv_conf.stat.exists

- name: Ensure EdgeNet directory exists
  file:
    path: /opt/edgenet
    state: directory
    mode: "0755"

- name: Ensure EdgeNet configuration is present
  template:
    src: edgenet-config.yaml.j2
    dest: /opt/edgenet/config.yaml
    mode: "0644"

- name: Ensure EdgeNet binary is present
  get_url:
    url: "{{ edgenet_node_url }}"
    # The checksum is necessary for Ansible to re-download the binary if it has changed.
    checksum: "{{ edgenet_node_checksum }}"
    dest: /opt/edgenet/node
    mode: "0755"
    timeout: 120

- name: Ensure EdgeNet service is present
  template:
    src: edgenet.service.j2
    dest: /etc/systemd/system/edgenet.service
    mode: "0644"

- name: Flush handlers
  meta: flush_handlers

- name: "Enable EdgeNet service (state={{ edgenet_service_state }})"
  systemd:
    name: edgenet
    state: "{{ edgenet_service_state }}"
    enabled: true
    daemon_reload: true
