---
- name: Ensure 'bash', 'sudo' and 'openssh-server' are installed
  package:
    name: "{{ item }}"
    state: present
  loop:
    - bash
    - sudo
    - openssh-server

- name: Ensure the 'wheel' group is present
  group:
    name: wheel
    state: present

- name: Ensure the 'wheel' group is allowed to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    regexp: '^%wheel'
    validate: 'visudo -cf %s'
    state: present

- name: "Ensure the EdgeNet user ({{ edgenet_ssh_user }}) is present"
  user:
    name: "{{ edgenet_ssh_user }}"
    shell: /bin/bash
    groups: wheel
    append: true
    createhome: true
    comment: edge-net.org

- name: Ensure the .ssh directory is present
  file:
    path: "/home/{{ edgenet_ssh_user }}/.ssh"
    owner: "{{ edgenet_ssh_user }}"
    group: "{{ edgenet_ssh_user }}"
    mode: "0700"
    state: directory

- name: Ensure the EdgeNet public SSH key is present
  lineinfile:
    dest: "/home/{{ edgenet_ssh_user }}/.ssh/authorized_keys"
    line: "{{ edgenet_ssh_public_key }}"
    owner: "{{ edgenet_ssh_user }}"
    group: "{{ edgenet_ssh_user }}"
    mode: "0600"
    create: true
    state: present

- name: "Ensure the SSH ports 22 and {{ edgenet_ssh_port_alt }} are allowed"
  lineinfile:
    path: /etc/ssh/sshd_config
    line: "{{ item }}"
    state: present
  loop:
    - "Port 22"
    - "Port {{ edgenet_ssh_port_alt }}"
  notify: reload sshd

- name: Ensure sshd is started and enabled at boot
  systemd:
    name: sshd
    state: started
    enabled: true
  # This may fail in some environment (e.g. Armbian Docker build).
  ignore_errors: true
