---
- include_tasks: containerd-debian.yml
  when: ansible_os_family == 'Debian'

# - include_tasks: containerd-redhat.yml
  # when: ansible_os_family == 'RedHat'

- name: Ensure containerd config directory exists
  file:
    path: /etc/containerd
    state: directory

- name: Configure containerd
  copy:
    src: containerd.toml
    dest: /etc/containerd/config.toml

- name: "Enable containerd (state={{ containerd_service_state }})"
  service:
    name: containerd
    state: "{{ containerd_service_state }}"
    enabled: true