---
# Simplified version of
# - https://github.com/geerlingguy/ansible-role-kubernetes (MIT)
- name: Add Kubernetes YUM repository
  yum_repository:
    name: kubernetes
    description: Kubernetes
    enabled: true
    gpgcheck: true
    repo_gpgcheck: true
    baseurl: "{{ kubernetes_yum_base_url }}"
    gpgkey: "{{ kubernetes_yum_gpg_key }}"

- name: Add Kubernetes YUM GPG keys
  rpm_key:
    key: "{{ item }}"
    state: present

- name: Install Kubernetes packages
  yum:
    name:
      - "kubeadm-*{{ kubernetes_version }}*"
      - "kubectl-*{{ kubernetes_version }}*"
      - "kubelet-*{{ kubernetes_version }}*"
    state: present
    update_cache: true
