---
- name: Install EdgeNet files
  copy:
    src: edgenet/
    dest: /opt/edgenet
    mode: "0755"

- name: Install EdgeNet service
  copy:
    src: systemd/edgenet.service
    dest: /etc/systemd/system/edgenet.service
    mode: "0644"

- name: Download kubeconfig file
  get_url:
    url: "{{ edgenet_kubeconfig_url }}"
    dest: /opt/edgenet/public.cfg
    mode: "0644"

- name: Disable swap
  command: swapoff -a

- name: Disable swap in /etc/fstab
  replace:
    path: /etc/fstab
    regexp: '^\s*[^#](.+swap\s+swap.+)$'
    replace: '# \1'
    backup: true

- name: Install required network utilities
  package:
    name:
      - ipset
      - iptables
      - net-tools
    state: present

- name: Install Docker (Debian x86-64)
  import_role:
    name: geerlingguy.docker
  vars:
    containerd_apt_arch: amd64
    docker_install_compose: false
    docker_package: "docker-ce=5:{{ edgenet_docker_version }}*"
  when:
    - ansible_os_family == 'Debian'
    - ansible_architecture == 'x86_64'

- name: Install Docker (Debian ARM64)
  import_role:
    name: geerlingguy.docker
  vars:
    containerd_apt_arch: arm64
    docker_install_compose: false
    docker_package: "docker-ce=5:{{ edgenet_docker_version }}*"
  when:
    - ansible_os_family == 'Debian'
    - ansible_architecture == 'aarch64'

- name: Install Docker (RedHat)
  import_role:
    name: geerlingguy.docker
  vars:
    docker_install_compose: false
    docker_package: "docker-ce-3:{{ edgenet_docker_version }}*"
  when: ansible_os_family == 'RedHat'

- name: Install Kubernetes
  include_tasks: kube.yml

- name: Configure Docker
  copy:
    src: docker/daemon.json
    dest: /etc/docker/daemon.json
    mode: "0644"

- name: Ensures NetworkManager conf.d exists
  file:
    path: /etc/NetworkManager/conf.d
    state: directory
    mode: "0755"

- name: Configure NetworkManager
  copy:
    src: NetworkManager/calico.conf
    dest: /etc/NetworkManager/conf.d/calico.conf
    mode: "0644"

# https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#letting-iptables-see-bridged-traffic
# https://kubernetes.io/docs/setup/production-environment/container-runtimes/
- name: Let iptables see bridged traffic
  sysctl:
    name: "{{ item }}"
    value: "1"
    state: present
  loop:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables
    - net.ipv4.ip_forward

# https://docs.projectcalico.org/maintenance/troubleshoot/troubleshooting#configure-networkmanager
- name: Increase conntrack table size
  sysctl:
    name: net.netfilter.nf_conntrack_max
    value: "1000000"
    state: present

# This is necessary since we have changed the daemon configuration
- name: Restart Docker
  systemd:
    name: docker
    enabled: yes
    state: restarted

- name: Enable EdgeNet service
  systemd:
    name: edgenet
    enabled: yes
    state: "{{ edgenet_service_state }}"

# Enable huge pages (Calico VPP requirement)
# NOTE: Disabled for now as it conflicts with postgres.
# - name: Enable Huge Pages
#   sysctl:
#     name: vm.nr_hugepages
#     value: "128"
#     state: present
