---
- name: Set the hostname
  hostname:
    name: "{{ edgenet_node_name }}.edgenet.io"

- name: Update /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: ".edgenet.io$"
    line: "127.0.0.1 {{ edgenet_node_name }}.edgenet.io"

- name: Install public IP update script
  copy:
    src: update-public-ip.sh
    dest: /usr/bin/update-public-ip.sh
    mode: "0755"

- name: Install public IP update systemd service
  copy:
    src: update-public-ip.service
    dest: /etc/systemd/system/update-public-ip.service
    mode: "0644"

- name: Enable public IP systemd service
  systemd:
    name: update-public-ip
    enabled: yes
    state: restarted

- name: Disable swap (as expected by Kubernetes)
  import_role:
    name: geerlingguy.swap
  vars:
    swap_file_state: absent

- name: Install Docker (Debian)
  import_role:
    name: geerlingguy.docker
  vars:
    docker_install_compose: false
    docker_package: "docker-ce=5:{{ edgenet_docker_version }}*"
  when: ansible_os_family == 'Debian'

- name: Install Docker (RedHat)
  import_role:
    name: geerlingguy.docker
  vars:
    docker_install_compose: false
    docker_package: "docker-ce-3:{{ edgenet_docker_version }}*"
  when: ansible_os_family == 'RedHat'

- name: Configure Docker daemon
  copy:
    src: docker-daemon.json
    dest: /etc/docker/daemon.json
    mode: "0644"
  notify: restart docker

# NOTE: EdgeNet is not yet tested with containerd.
# - name: Install containerd
#   import_role:
#     name: containerd

- name: Install Kubernetes
  import_role:
    name: geerlingguy.kubernetes
  vars:
    kubernetes_role: "" # We do not want the role to run `kubeadm join` for us.
    kubernetes_version: "{{ edgenet_kubernetes_version }}"
    kubernetes_version_rhel_package: "0:{{ edgenet_kubernetes_version }}*"

# https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#letting-iptables-see-bridged-traffic
# https://kubernetes.io/docs/setup/production-environment/container-runtimes/
- name: Let iptables see bridged traffic
  sysctl:
    name: "{{ item }}"
    value: "1"
    state: present
  loop:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables
    - net.ipv4.ip_forward

# Enable huge pages (Calico VPP requirement)
# NOTE: Disabled for now as it conflicts with postgres.
# - name: Enable Huge Pages
#   sysctl:
#     name: vm.nr_hugepages
#     value: "128"
#     state: present
