name: Tests

on:
  push:
    paths-ignore: ['**.md']
  pull_request:
    paths-ignore: ['**.md']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./bootstrap.sh
        env:
          EDGENET_REPOSITORY: file://${{ github.workspace }}
          EDGENET_REF: ${{ github.sha }}
