name: Tests

on:
  push:
    paths-ignore: ['**.md']
  pull_request:
    paths-ignore: ['**.md']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bootstrap
        run: |
          ./bootstrap.sh
        env:
          EDGENET_REPOSITORY: file:///home/runner/work/node/node
          EDGENET_REF: ${{ env.GITHUB_REF }}
