---
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install containerd.
  package:
    name: "{{ containerd_package }}"
    state: "{{ containerd_package_state }}"
  notify: restart containerd

- name: Ensure /etc/containerd exists.
  file:
    path: /etc/containerd
    state: directory
    mode: "0755"

- name: Configure containerd.
  command:
    cmd: containerd config default > /etc/containerd/config.toml
    creates: /etc/containerd/config.toml
  notify: restart containerd

- name: Ensure containerd is started and enabled at boot.
  service:
    name: containerd
    state: "{{ containerd_service_state }}"
    enabled: "{{ containerd_service_enabled }}"

- name: Configure kernel modules.
  copy:
    src: containerd-modules.conf
    dest: /etc/modules-load.d/containerd.conf
    mode: "0644"

- name: Load kernel modules.
  modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - br_netfilter
    - overlay

- name: Ensure handlers are notified now to avoid firewall conflicts.
  meta: flush_handlers
